# Utiliser l'image MongoDB noble comme base
FROM mongo:noble

# Définir l'emplacement où MongoDB stockera les données
VOLUME /data/db

# Exposer le port par défaut de MongoDB
EXPOSE 27017

# Commande par défaut pour démarrer MongoDB
CMD ["mongod"]

